name: Build Infra for MLflow on Azure 

on:
  push:
    branches:
      - master
      - feature/adding_terraform_taskk
    paths:
      - 'infrastructure/azure/**'
      - '.github/workflows/azure/deploy_on_azure.yaml'
  workflow_dispatch:
  
jobs:
  terraform:
    runs-on: ubuntu-latest 
    env:
      ARM_CLIENT_ID: ${{ secrets.INFRA_AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.INFRA_AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.INFRA_AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.INFRA_AZURE_AD_TENANT_ID }}
      TF_VERSION: 1.5.7
      TERRAFORM_WORKING_DIR: "azure"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ env.TERRAFORM_WORKING_DIR }}

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.TERRAFORM_WORKING_DIR }}
        env:
          TF_VAR_resource_group_name: ${{ vars.ABCD_AZURE_RESOURCE_GROUP_NAME }}
          TF_VAR_location: ${{ vars.ABCD_AZURE_RG_LOCATION }}

      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ env.TERRAFORM_WORKING_DIR }}
          
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: ${{ env.TERRAFORM_WORKING_DIR }}
        env:
          TF_VAR_resource_group_name: ${{ vars.ABCD_AZURE_RESOURCE_GROUP_NAME }}
          TF_VAR_location: ${{ vars.ABCD_AZURE_RG_LOCATION }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: ${{ env.TERRAFORM_WORKING_DIR }}
        env:
          TF_VAR_resource_group_name: ${{ vars.ABCD_AZURE_RESOURCE_GROUP_NAME }}
          TF_VAR_location: ${{ vars.ABCD_AZURE_RG_LOCATION }}
