name: Create Custom MLflow Image
env:
  AZURE_CONTAINER_REGISTRY_NAME: "mlflowcloudacr"
  IMAGE_NAME: "gilsamas/mlflowcloud"
on: 
  push:
    branches: 
      - "main"
      - "master"
      - "feature/adding_terraform_taskk"
    paths:
      - "docker/Dockerfile"

  pull_request:
    branches:
      - "main"
      - "master"
  workflow_dispatch:

jobs:   
  build_and_push_image:
    needs: 
      - create_acr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker Image to ACR
        uses: azure/cli@v2
        with:
          inlineScript: |
            az acr build \
              --registry $AZURE_CONTAINER_REGISTRY_NAME \
              --image ${{ env.IMAGE_NAME }}:${{ github.sha }} ./docker 